// src/lib/components/game/ActionButtons.svelte
<script lang="ts">
	import { applyPlayerAction, gameStore, humanPlayer, isHumanTurn } from '$stores/gameStore';
	import { getValidActions, getCallAmount, getMinRaise } from '$game/rules/BettingRules';
	import { createAction } from '$game/models/Action';
	import type { ActionType } from '$game/models/Action';

	interface Props {
		onRaiseClick?: () => void;
	}

	let { onRaiseClick }: Props = $props();

	let showRaiseSlider = $state(false);
	let raiseAmount = $state(0);

	const validActions = $derived<ActionType[]>(
		$gameStore && $humanPlayer ? getValidActions($gameStore, $humanPlayer.id) : []
	);

	const callAmount = $derived(
		$gameStore && $humanPlayer ? getCallAmount($gameStore, $humanPlayer.id) : 0
	);

	const minRaise = $derived(
		$gameStore && $humanPlayer ? getMinRaise($gameStore, $humanPlayer.id) : 0
	);

	const maxRaise = $derived($humanPlayer?.chips || 0);

	function handleFold() {
		if (!$humanPlayer) return;
		applyPlayerAction(createAction('fold', $humanPlayer.id, 0));
	}

	function handleCheck() {
		if (!$humanPlayer) return;
		applyPlayerAction(createAction('check', $humanPlayer.id, 0));
	}

	function handleCall() {
		if (!$humanPlayer) return;
		const amount = Math.min(callAmount, $humanPlayer.chips);
		applyPlayerAction(createAction('call', $humanPlayer.id, amount));
	}

	function handleBet() {
		if (!$humanPlayer) return;
		showRaiseSlider = true;
		raiseAmount = minRaise;
		onRaiseClick?.();
	}

	function handleRaise() {
		if (!$humanPlayer) return;
		showRaiseSlider = true;
		raiseAmount = minRaise;
		onRaiseClick?.();
	}

	function handleAllIn() {
		if (!$humanPlayer) return;
		applyPlayerAction(createAction('all-in', $humanPlayer.id, $humanPlayer.chips));
	}

	function confirmRaise() {
		if (!$humanPlayer) return;
		const actionType = $gameStore?.currentBet === 0 ? 'bet' : 'raise';
		applyPlayerAction(createAction(actionType, $humanPlayer.id, raiseAmount));
		showRaiseSlider = false;
	}

	function cancelRaise() {
		showRaiseSlider = false;
	}

	$effect(() => {
		if (showRaiseSlider) {
			raiseAmount = minRaise;
		}
	});
</script>

{#if $isHumanTurn && $humanPlayer}
	<div class="flex flex-col gap-4 bg-gray-800 p-4 rounded-lg shadow-xl">
		{#if !showRaiseSlider}
			<div class="flex gap-2 flex-wrap">
				{#if validActions.includes('fold')}
					<button
						onclick={handleFold}
						class="px-6 py-3 bg-red-600 hover:bg-red-700 text-white font-bold rounded-lg transition-colors"
					>
						Fold
					</button>
				{/if}

				{#if validActions.includes('check')}
					<button
						onclick={handleCheck}
						class="px-6 py-3 bg-gray-600 hover:bg-gray-700 text-white font-bold rounded-lg transition-colors"
					>
						Check
					</button>
				{/if}

				{#if validActions.includes('call')}
					<button
						onclick={handleCall}
						class="px-6 py-3 bg-blue-600 hover:bg-blue-700 text-white font-bold rounded-lg transition-colors"
					>
						Call ${callAmount}
					</button>
				{/if}

				{#if validActions.includes('bet')}
					<button
						onclick={handleBet}
						class="px-6 py-3 bg-green-600 hover:bg-green-700 text-white font-bold rounded-lg transition-colors"
					>
						Bet
					</button>
				{/if}

				{#if validActions.includes('raise')}
					<button
						onclick={handleRaise}
						class="px-6 py-3 bg-green-600 hover:bg-green-700 text-white font-bold rounded-lg transition-colors"
					>
						Raise
					</button>
				{/if}

				{#if validActions.includes('all-in')}
					<button
						onclick={handleAllIn}
						class="px-6 py-3 bg-yellow-600 hover:bg-yellow-700 text-white font-bold rounded-lg transition-colors"
					>
						All-In (${$humanPlayer.chips})
					</button>
				{/if}
			</div>
		{:else}
			<!-- Raise Slider -->
			<div class="flex flex-col gap-3">
				<div class="flex justify-between items-center">
					<span class="text-white font-semibold">Raise Amount: ${raiseAmount}</span>
					<button
						onclick={cancelRaise}
						class="text-gray-400 hover:text-white transition-colors"
					>
						✕
					</button>
				</div>

				<input
					type="range"
					bind:value={raiseAmount}
					min={minRaise}
					max={maxRaise}
					step={Math.max(1, Math.floor(($gameStore?.smallBlind || 10) / 2))}
					class="w-full h-2 bg-gray-700 rounded-lg appearance-none cursor-pointer slider"
				/>

				<div class="flex justify-between text-sm text-gray-400">
					<span>Min: ${minRaise}</span>
					<span>Max: ${maxRaise}</span>
				</div>

				<div class="flex gap-2">
					<button
						onclick={confirmRaise}
						class="flex-1 px-6 py-3 bg-green-600 hover:bg-green-700 text-white font-bold rounded-lg transition-colors"
					>
						Confirm ${raiseAmount}
					</button>
					<button
						onclick={cancelRaise}
						class="px-6 py-3 bg-gray-600 hover:bg-gray-700 text-white font-bold rounded-lg transition-colors"
					>
						Cancel
					</button>
				</div>
			</div>
		{/if}
	</div>
{:else}
	<div class="bg-gray-800 p-4 rounded-lg shadow-xl">
		<p class="text-gray-400 text-center">Waiting for other players...</p>
	</div>
{/if}

<style>
	.slider::-webkit-slider-thumb {
		appearance: none;
		width: 20px;
		height: 20px;
		background: #10b981;
		cursor: pointer;
		border-radius: 50%;
	}

	.slider::-moz-range-thumb {
		width: 20px;
		height: 20px;
		background: #10b981;
		cursor: pointer;
		border-radius: 50%;
		border: none;
	}
</style>

// components/game/action-buttons.tsx
'use client';

import { useState } from 'react';
import { useGameStore } from '@/lib/stores/game-store';
import { createAction } from '@/lib/game-logic/models/Action';
import { bettingRules } from '@/lib/game-logic/rules/BettingRules';
import { cn } from '@/lib/utils/cn';

export function ActionButtons() {
  const { players, currentPlayerIndex, processPlayerAction, phase } = useGameStore();
  const [raiseAmount, setRaiseAmount] = useState<number | null>(null);

  if (phase === 'waiting' || phase === 'complete') {
    return null;
  }

  const currentPlayer = players[currentPlayerIndex];
  if (!currentPlayer || currentPlayer.isBot) {
    return (
      <div className="text-center text-white">
        <div className="text-lg">{currentPlayer?.name}'s turn...</div>
      </div>
    );
  }

  const gameState = useGameStore.getState();
  const validActions = bettingRules.getValidActions(gameState, currentPlayer);

  const handleFold = () => {
    processPlayerAction(createAction('fold', currentPlayer.id));
  };

  const handleCheck = () => {
    processPlayerAction(createAction('check', currentPlayer.id));
  };

  const handleCall = () => {
    processPlayerAction(createAction('call', currentPlayer.id, validActions.callAmount));
  };

  const handleRaise = (customAmount?: number) => {
    const amount = customAmount || raiseAmount || validActions.minRaise;
    const finalAmount = Math.min(amount, currentPlayer.chips);
    processPlayerAction(createAction('raise', currentPlayer.id, finalAmount));
    setRaiseAmount(null); // Reset after action
  };

  const handleAllIn = () => {
    processPlayerAction(createAction('all-in', currentPlayer.id, currentPlayer.chips));
  };

  // Initialize raise amount to minimum if not set
  const currentRaiseAmount = raiseAmount || validActions.minRaise;

  return (
    <div className="flex flex-col items-center gap-4">
      <div className="text-center text-white">
        <div className="text-lg font-bold">Your Turn!</div>
        <div className="text-sm">Choose your action</div>
      </div>

      {/* Raise Slider */}
      {validActions.canRaise && (
        <div className="w-full max-w-md rounded-lg bg-black/30 p-4">
          <div className="mb-2 flex justify-between text-sm text-white">
            <span>Raise Amount:</span>
            <span className="font-bold text-yellow-400">${currentRaiseAmount}</span>
          </div>
          <input
            type="range"
            min={validActions.minRaise}
            max={currentPlayer.chips}
            step={gameState.settings.bigBlind}
            value={currentRaiseAmount}
            onChange={(e) => setRaiseAmount(Number(e.target.value))}
            className="w-full cursor-pointer accent-yellow-500"
          />
          <div className="mt-1 flex justify-between text-xs text-white/70">
            <span>Min: ${validActions.minRaise}</span>
            <span>Max: ${currentPlayer.chips}</span>
          </div>
        </div>
      )}

      <div className="flex gap-3">
        <button
          onClick={handleFold}
          className="rounded-lg bg-red-600 px-6 py-3 font-bold text-white shadow-lg transition hover:bg-red-700"
        >
          Fold
        </button>

        {validActions.canCheck && (
          <button
            onClick={handleCheck}
            className="rounded-lg bg-blue-600 px-6 py-3 font-bold text-white shadow-lg transition hover:bg-blue-700"
          >
            Check
          </button>
        )}

        {validActions.canCall && (
          <button
            onClick={handleCall}
            className="rounded-lg bg-green-600 px-6 py-3 font-bold text-white shadow-lg transition hover:bg-green-700"
          >
            Call ${validActions.callAmount}
          </button>
        )}

        {validActions.canRaise && (
          <button
            onClick={() => handleRaise()}
            className="rounded-lg bg-yellow-600 px-6 py-3 font-bold text-white shadow-lg transition hover:bg-yellow-700"
          >
            Raise ${currentRaiseAmount}
          </button>
        )}

        {validActions.canAllIn && (
          <button
            onClick={handleAllIn}
            className="rounded-lg bg-purple-600 px-6 py-3 font-bold text-white shadow-lg transition hover:bg-purple-700"
          >
            All-In ${currentPlayer.chips}
          </button>
        )}
      </div>
    </div>
  );
}
